### PR TITLE
Adding in notempty / endnotempty

### PR DESCRIPTION
**Pull request by shanejones**
Added a few extra directives for checking data against `empty()` 

Given them a test locally and all works great.

### CODE REVIEW

**Comment by Log1x** [comment]
[`@empty`](https://laravel.com/docs/master/blade#if-statements) already exists but I'm cool with adding a `! empty()` equivalent.

I prefixed `null` with `is` such as `@isnull` and `@isnotnull` but seeing as in Laravel, `@empty` has no prefix– let's keep with their standards.

`@notempty` and `@endnotempty`?

**Comment by shanejones** [comment]
Thanks for the feedback. PR is now updated.

**Comment by Log1x** [comment]
No problem! Can you fix the indenting? I know prettifier/beautifier probably changed it on save as the indenting isn't exactly "traditional" with the directives (they are ugly lol)

sorry :x

**Comment by shanejones** [comment]
That should now be updated for you.

**Pull request merged**
